### PR TITLE
First shot for a basic monitoring page (http://ip:port/status)

### PR DESCRIPTION
**Pull request by TheTroll**
Hi,

this is a first shot for issue https://github.com/catalinii/minisatip/issues/158.

I took some inspiration from https://github.com/perexg/minisatip/blob/d8f2c0e7b1ab2ea3d87b05325d1894c180861791/adapter.c#L1002 as well...

### CODE REVIEW

**Comment by catalinii** [comment]
Hi,

as I took some commits from your repository I will close this pull request.

Thanks

**Comment by TheTroll** [comment]
Hi,

understood, sorry I did not have much time to pull request ... And your code has changed so much that it makes it difficult :)

**Comment by catalinii** [comment]
no problem, thanks for the contributing :)

**Comment by pbriesch** [comment]
Please add the fact to the README that there is a status page available and mention its html port number.

Thanks, Paul

**Comment by catalinii** [comment]
I have added it to the Readme... Thank you :)

**Pull request closed without merging**
