### PR TITLE
Add Debian packaging

### PR DESCRIPTION
**Pull request by Jalle19**
@marillat let's continue the discussion here

### CODE REVIEW

**Comment by Jalle19** [comment]
@marillat what's the command to build a .deb package? I could add it to the CI/CD pipeline, then we can start refining it.

**Comment by marillat** [comment]
dpkg-buildpackage from dpkg-dev package

**Comment by marillat** [comment]
I added a minisatip user to start minisatip with systemd in 1.2.10-dmo2

**Comment by Jalle19** [comment]
@marillat awesome, I incorporated the changes here and amended the commits to make you the author.

What's next here? I guess we should document how to build a package, then I can test that it actually works (I happen to run minisatip on Debian too, but so far I've manually installed it and hacked together a similar systemd unit).

**Comment by Jalle19** [comment]
@marillat please review my last three commits, are they okay?

**Comment by marillat** [comment]
We have the same debian directory (except  [ade0252](https://github.com/catalinii/minisatip/pull/986/commits/ade0252f742b0f80423e371e790594ad19be3d74)) so it's perfect.

**Review by catalinii — APPROVED** [review]

**Comment by Jalle19** [comment]
@marillat can we drop the `nodejs-jquery` dependency? The file is after all bundled here and I don't see that changing any time soon.

Also, can we change the package name to just `minisatip` instead of `minisatip-dmo`?

**Comment by Jalle19** [comment]
Not really sure how we could automate the generation of new packages (with bumped version number and associated change log entries), I would need help with that. Would definitely be easier if we didn't do automatic releases :/

@catalinii @marillat thoughts?

**Comment by marillat** [comment]
> @marillat can we drop the `nodejs-jquery` dependency? The file is after all bundled here and I don't see that changing any time soon.
> 
> Also, can we change the package name to just `minisatip` instead of `minisatip-dmo`?

Yes you can drop `nodejs-jquery` and remove -dmo to the source name. Should be done in the control and changelog files.

**Comment by marillat** [comment]
> Not really sure how we could automate the generation of new packages (with bumped version number and associated change log entries), I would need help with that. Would definitely be easier if we didn't do automatic releases :/

automatic release is boring must be done by an human.

**Comment by catalinii** [comment]
@Jalle19

Generally it needs to be added to this list of files: https://github.com/catalinii/minisatip/blob/master/.github/workflows/binaries.yml#L51

 If needed, I can do that (posting debian package in the binary section).

**Comment by Jalle19** [comment]
@marillat can you review the last few commits?

**Comment by marillat** [comment]
seems to be OK.

**Comment by Jalle19** [comment]
Haven't gotten around to testing the package yet, but let's merge this and continue iterating

**Comment by marillat** [comment]
I noticed that debhelper-compat version has been downgraded from 13 to 12, Why ?

**Comment by marillat** [comment]
I noticed that deluser is called with --quiet
Probably a bad idea if  something goes wrong user will never seen the deluser errors.

**Comment by Jalle19** [comment]
> I noticed that debhelper-compat version has been downgraded from 13 to 12, Why ?

Ubuntu 22.04 doesn't have 13, so I didn't manage to build it without lowering compat to 12.

**Comment by Jalle19** [comment]
Feel free to make pull requests if you have improvements!

**Pull request merged**
