### PR TITLE
Add pid 18 to be sent to the DDCI

### PR DESCRIPTION
**Pull request by catalinii**

### CODE REVIEW

**Comment by Jalle19** [comment]
What does this do?

**Comment by catalinii** [comment]
It maps pid 18 to the first pmt. My CAM needs this to update regularly.

**Comment by Jalle19** [comment]
Getting a lot of this after this commit:

```
PID Continuity error (adapter 0, pos 132): pid: 1016, Expected CC: 8, Actual CC: 4, CC Before 7
```

**Comment by catalinii** [comment]
I get that too ...was thinking is specific to my provider/ setup

**Comment by catalinii** [comment]
Will look into it

**Comment by Jalle19** [comment]
Saw that you reverted this. Is ddci_create_epg() really needed? It seems pretty arbitrary.

**Comment by catalinii** [comment]
Certain CAMs does not request pin number when switching the channel when ddci_create_epg is used. Will investigate more when my CAM disables next time.

**Comment by Jalle19** [comment]
What if you add PID 18 like you did but disable ddci_create_epg()?

**Comment by catalinii** [comment]
I am not even sure pid 18 helps my case. But if I do that, I will choose for my CAM to work (which is an old model) over an official CAM that is used a lot across Europe.

**Pull request merged**
