### PR TITLE
progress-bar-rewrite

### PR DESCRIPTION
**Pull request by kellerman**
Progress bars rewritten to a pure HTML/CSS solution.
pBar jQuery plugin removed.
Added dB display over SNR progress bar.
Added animation for the progress bars when the table is being updated.
Color scale depending of the value (5 colors)

Preview https://i.imgur.com/tDuWPJc.png
Open to any modifications to colors, borders, brightness, opacity etc...

### CODE REVIEW

**Comment by catalinii** [comment]
@kellerman at high level it looks good.

The only question I have is related to the value 16.5. I see it is always displaying that value?
Can that be replaced with the raw value?
If we need to export it we can

**Comment by kellerman** [comment]
@lars18th 
The variable is set to 16.5 for testing, it shold be replaced with the real value/10.

**Comment by lars18th** [comment]
Hi @catalinii ,

I'm working no implementing the capture of the dB to finish this patch. Please watch out for changes.

**Comment by catalinii** [comment]
@lars18th I will merge @kellerman's changes, feel free to rebase on top of his changes

**Comment by lars18th** [comment]
> @lars18th I will merge @kellerman's changes, feel free to rebase on top of his changes

OK, I'll do it @catalinii .

**Comment by lars18th** [comment]
>> @lars18th I will merge @kellerman's changes, feel free to rebase on top of his changes

>OK, I'll do it @catalinii .

Done @catalinii !

**Pull request merged**
