### PR TITLE
Use writev on axe devices

### LINKED ISSUE #795: sendmmsg(): errno 38: Function not implemented
Reported here: https://github.com/Jalle19/satip-axe/issues/3

satip-axe runs Linux 2.6, while `sendmmsg` was introduced in Linux 3.0 (https://man7.org/linux/man-pages/man2/sendmmsg.2.html)

https://github.com/catalinii/minisatip/issues/346 seems to be related - apparently the Android NDK doesn't expose `sendmmsg` either.

@catalinii what do you suggest? The ifdef should probably be extended somehow.

### PR DESCRIPTION
**Pull request by melias122**
Fixes #795
Fixes https://github.com/Jalle19/satip-axe/issues/3

### CODE REVIEW

**Comment by melias122** [comment]
Tried `if defined(__APPLE__) || defined(AXE)`, but that lead to
```
socketworks.c:1227:5: error: conflicting types for 'sendmmsg'
 int sendmmsg(int rsock, struct mmsghdr *msg, int len, int t) {
     ^
In file included from /opt/STM/STLinux-2.4/devkit/sh4/target/usr/include/sys/socket.h:40:0,
                 from /opt/STM/STLinux-2.4/devkit/sh4/target/usr/include/netinet/in.h:25,
                 from /opt/STM/STLinux-2.4/devkit/sh4/target/usr/include/arpa/inet.h:23,
                 from socketworks.c:20:
/opt/STM/STLinux-2.4/devkit/sh4/target/usr/include/bits/socket.h:437:12: note: previous declaration of 'sendmmsg' was here
 extern int sendmmsg (int __fd, struct mmsghdr *__vmessages,
            ^

```

**Comment by catalinii** [comment]
Where do u have axe sdk from?

**Comment by Jalle19** [comment]
I'm personally using https://github.com/Jalle19/docker-centos7-stlinux24/blob/master/Dockerfile

**Comment by Jalle19** [comment]
It's a bit tricky because sendmmsg() is defined in glibc, it's just not implemented in the kernel.

Maybe the only solution is to simply not use sendmmsg() anywhere?

**Comment by melias122** [comment]
I am using satip-axe. 

Not using sendmmsg will be simplest, but I am not sure about performace of writev vs sendmmsg.

Martin Elias

**Comment by catalinii** [comment]
@Jalle19 probably is better if you define this method as:
sendmmsg0(int rsock, struct mmsghdr *msg, int len, int t)

and for axe and MAc os just do:
#define sendmmsg(a,b,c,d) sendmmsg0(a,b,c,d)

**Comment by melias122** [comment]
@catalinii, updated PR, but it is not tested yet

**Comment by catalinii** [comment]
Looks good from my point of view. If you guys don't manage to test it on axe as I do not have one will try on MAC.

**Comment by melias122** [comment]
I will test it during the day, when nobody is watching tv in the house and let you know.

Martin Elias

**Comment by Jalle19** [comment]
I use TCP so I'm not affected by this :D

**Comment by Jalle19** [comment]
@melias122 did you get around to testing this?

**Comment by melias122** [comment]
Yes, it works fine on digibit r1.

**Pull request merged**
