### PR TITLE
Don't manipulate PMT IDs in the filter even when clean_psi is not used

### PR DESCRIPTION
**Pull request by Jalle19**
Been running this locally for some time, haven't at least noticed any side effects.

### CODE REVIEW

**Comment by Jalle19** [comment]
Mentioned here https://github.com/catalinii/minisatip/issues/949#issuecomment-1337858224

**Comment by catalinii** [comment]
clean_psi is broken, but other than that I am fine with it.

**Comment by catalinii** [comment]
I do not remember why I did it that way, probably to mark the PMT pid for a pmt and to distinguish it from the actual streampids which are positive.

**Review by catalinii — APPROVED** [review]

**Comment by Jalle19** [comment]
Should we remove clean_psi if it's broken?

**Comment by lars18th** [comment]
Hi @Jalle19 ,

The `clean_psi` is now removed by @catalinii . Therefore, this PR continues having sense? Or you need to refactor it?

**Comment by Jalle19** [comment]
I'll rebase and check

**Comment by Jalle19** [comment]
Rebased

**Comment by Jalle19** [comment]
No, two weeks is not two years

**Comment by catalinii** [comment]
Feel free to merge when ready

**Pull request merged**
