### PR TITLE
Support new elements, most importantly "Critical Security Update Version"

### LINKED ISSUE #1029: PID not found CI+ CAM after ~15 min of playback
Channel stops being decoded by CI+ cam and minisatip throws error that PID, responsible for CA is not found, which is not true. Gets resolved by minisatip full restart.

http://192.168.10.227:8082/?fe=-1&src=1&freq=10727&pol=H&msys=DVBS2&sr=30000&pids=0,1,17,16,18,6040,6041,6042,6043,6044,6045,6046

[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 18 for fd 12 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6040 for fd 21 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6041 for fd 22 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6042 for fd 23 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6043 for fd 24 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6044 for fd 25 [0 ms]
[29/12 00:00:52.883 main]: AD 2 [dvr 2 0], setting filter on PID 6045 for fd 26 [0 ms]
[29/12 00:00:52.884 main]: AD 2 [dvr 2 0], setting filter on PID 6046 for fd 27 [0 ms]
[29/12 00:00:52.884 main]: Reply (handle 11) [192.168.10.227:27530] content_len:0, sock 11
[29/12 00:00:52.923 AD2]: Sending PMT 2 to all CAs: ad_ca_mask 1, pmt_ca_mask 0, disabled_ca_mask 0
[29/12 00:00:52.923 AD2]: CAID 1856 and mask FFFF matched PMT 2
[29/12 00:00:52.923 AD2]: PMT CA 2 pmt 2 pid 6040 (Museum 4K) ver 5 sid 4604 (4604), enabled_pmts 1, CLM_UPDATE, PMTS to be send 2 -1, pos 0
[29/12 00:00:52.923 AD2]: ca_write_apdu: CA 2, session 7, name EN50221_APP_CA_RESOURCEID, write tag 9F8032, data length 432
[29/12 00:00:52.991 AD2]: cw already exist at position 0: id 0, parity 0, pmt 2, time 1508858 ms ago, expiry in 2091142 ms, CW: AF 5B EE F4 DF C1 90 52, IV: BD 18 24 54 46 F5 4C 65
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6041 while processing the PAT
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6042 while processing the PAT
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6043 while processing the PAT
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6044 while processing the PAT
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6045 while processing the PAT
[29/12 00:00:52.991 AD2]: Found PMT 2 active with pid 6046 while processing the PAT
[29/12 00:00:52.991 AD2]: found CW: 0 [not validated] for Museum 4K PMT 2, old cw -1, packets 324, parity 0, pid 6040: id 0, parity 0, pmt 2, time 1508858 ms ago, expiry in 2091142 ms, CW: AF 5B EE F4 >
[29/12 00:00:52.991 AD2]: Start streaming for stream sid 1, len 61476 to handle 11 => 192.168.10.227:27530
[29/12 00:00:52.992 AD2]: found CW: -1 [validated] for Museum 4K PMT 2, old cw 0, packets 531, parity 0, **pid 6040: not found**
[29/12 00:00:53.154 signal]: BW 1705 KB/s, DMX 3038 KB/s, Buffered 0 MB, Total BW: 3872 MB, ns/read 3255, r: 23, w: 47 fw: 0, tt: 74 ms
[29/12 00:00:54.168 signal]: BW 1719 KB/s, DMX 3173 KB/s, Buffered 0 MB, Total BW: 3873 MB, ns/read 288, r: 25, w: 50 fw: 0, tt: 7 ms
[29/12 00:00:55.178 signal]: BW 1729 KB/s, DMX 3193 KB/s, Buffered 0 MB, Total BW: 3875 MB, ns/read 292, r: 25, w: 50 fw: 0, tt: 7 ms
[29/12 00:00:56.204 signal]: BW 1724 KB/s, DMX 3180 KB/s, Buffered 0 MB, Total BW: 3877 MB, ns/read 261, r: 25, w: 50 fw: 0, tt: 6 ms
[29/12 00:00:57.218 signal]: BW 1657 KB/s, DMX 3060 KB/s, Buffered 0 MB, Total BW: 3879 MB, ns/read 263, r: 24, w: 48 fw: 0, tt: 6 ms
[29/12 00:00:58.233 signal]: BW 1722 KB/s, DMX 3182 KB/s, Buffered 0 MB, Total BW: 3880 MB, ns/read 272, r: 25, w: 50 fw: 0, tt: 6 ms
[29/12 00:00:59.250 signal]: BW 1728 KB/s, DMX 3189 KB/s, Buffered 0 MB, Total BW: 3882 MB, ns/read 264, r: 25, w: 50 fw: 0, tt: 6 ms
[29/12 00:01:00.264 signal]: BW 1651 KB/s, DMX 3048 KB/s, Buffered 0 MB, Total BW: 3884 MB, ns/read 269, r: 24, w: 48 fw: 0, tt: 6 ms
[29/12 00:01:01.278 signal]: BW 1730 KB/s, DMX 3192 KB/s, Buffered 0 MB, Total BW: 3885 MB, ns/read 262, r: 25, w: 50 fw: 0, tt: 6 ms
[29/12 00:01:02.297 signal]: BW 1721 KB/s, DMX 3176 KB/s, Buffered 0 MB, Total BW: 3887 MB, ns/read 264, r: 25, w: 50 fw: 0, tt: 6 ms
[29/12 00:01:03.311 signal]: BW 1660 KB/s, DMX 3065 KB/s, Buffered 0 MB, Total BW: 3889 MB, ns/read 266, r: 24, w: 48 fw: 0, tt: 6 ms
[29/12 00:01:03.882 main]: select_and_execute[11]: Close on socket 11 (sid:1) from 192.168.10.227:27530 - type http (3) errno 0
[29/12 00:01:03.882 main]: Requested sid close 1 timeout 30000 type 1, sock 11, handle 11, timeout 0

### LINKED ISSUE #1090: Not descrambling if FTA tuned from the same TP in certain order
Bump this one up https://github.com/catalinii/minisatip/issues/1029, seems ticket got lost
minisatip-1.2.102 still persists

### LINKED ISSUE #1134: CI+ descrambling randomly stops until manually restarted
As per https://github.com/catalinii/minisatip/issues/1029
Problem persists in all versions. It can play for days or it can play only for 5-15 minutes and I have keep minisatip restarting to get it work again.
[minisatip2.log](https://github.com/catalinii/minisatip/files/13401490/minisatip2.log)

[18/11 23:30:47.546 main]: BW 1378 KB/s, DMX 1378 KB/s, Buffered 0.0 MB, Dropped: 0.0 MB, ns/read 684, r: 25, w: 25 fw: 0, tt: 17 ms
[18/11 23:30:48.560 main]: BW 1383 KB/s, DMX 1383 KB/s, Buffered 0.0 MB, Dropped: 0.0 MB, ns/read 705, r: 25, w: 25 fw: 0, tt: 17 ms
[18/11 23:30:49.580 main]: BW 1321 KB/s, DMX 1321 KB/s, Buffered 0.0 MB, Dropped: 0.0 MB, ns/read 756, r: 24, w: 24 fw: 0, tt: 18 ms
**[18/11 23:30:50.119 AD2]: Parity change for Museum 4K PMT 3, new active parity 1 pid 6041 [47 17 99 DA 7E 6C C9]
[18/11 23:30:50.119 AD2]: found CW: -1 [validated] for Museum 4K PMT 3, old cw 0, packets 164, parity 1, pid 6040: not found**

Play link: http://localhost:8082/?fe=-1&src=1&freq=10727&pol=H&msys=DVBS2&sr=30000&pids=0,1,17,16,18,6040,6041

Why does it switch to 6041 as a new parity and throws 6040 away? And it gets back to 6040 after I restart it.
Excluding 6040 from the link makes it unplayable.

1.3.0

### PR DESCRIPTION
**Pull request by Jalle19**
Should fix:

```
[30/12 20:01:53.761 AD2]: req element 49
[30/12 20:01:53.761 AD2]: element_get: invalid id
[30/12 20:01:53.761 AD2]: can not get element 49
[30/12 20:01:53.761 AD2]: cannot get element 49
[30/12 20:01:53.761 AD2]: cannot req data
```

@Delitants can you try your CAM again with this change?

Fixes #1029, fixes #1090, fixes #1134

### CODE REVIEW

**Comment by Delitants** [comment]
> Should fix:
> 
> ```
> [30/12 20:01:53.761 AD2]: req element 49
> [30/12 20:01:53.761 AD2]: element_get: invalid id
> [30/12 20:01:53.761 AD2]: can not get element 49
> [30/12 20:01:53.761 AD2]: cannot get element 49
> [30/12 20:01:53.761 AD2]: cannot req data
> ```
> 
> @Delitants can you try your CAM again with this change?

Zero effect, same errors

[25/06 10:34:57.041 AD2]: RECV ciplus cc msg CAM2, session_num 6, tag 9f9007 len 40 dt_id 0
[25/06 10:34:57.041 AD2]: auth ok!
[25/06 10:34:57.041 AD2]: serial sac data req: 4
[25/06 10:34:57.041 AD2]: req element 49
[25/06 10:34:57.041 AD2]: element_get: invalid id
[25/06 10:34:57.041 AD2]: can not get element 49
[25/06 10:34:57.041 AD2]: cannot get element 49
[25/06 10:34:57.041 AD2]: cannot req data
[25/06 10:34:58.097 AD2]: READ TPDU: :

**Comment by Jalle19** [comment]
That is not possible, please make doubly sure you re-compile minisatip from the correct branch

**Comment by Delitants** [comment]
> That is not possible, please make doubly sure you re-compile minisatip from the correct branch

I've literally went to my folder, applied the changes, did make clean, configure make and restarted. No effect:

[25/06 10:42:50.261 AD2]: RECV ciplus cc msg CAM2, session_num 6, tag 9f9007 len 40 dt_id 0
[25/06 10:42:50.261 AD2]: auth ok!
[25/06 10:42:50.261 AD2]: serial sac data req: 4
[25/06 10:42:50.261 AD2]: req element 49
[25/06 10:42:50.261 AD2]: element_get_buf: datatype 49 not valid
[25/06 10:42:50.261 AD2]: can not get element 49
[25/06 10:42:50.261 AD2]: cannot get element 49
[25/06 10:42:50.261 AD2]: cannot req data
[25/06 10:42:51.308 AD2]: READ TPDU: :
  0000  00 01 80 02 01 80

**Comment by Jalle19** [comment]
This time you applied the change, not last time. There's a different message now.

**Comment by Jalle19** [comment]
Try removing the .bin file for your CAM from /var/cache/minisatip and try again

**Comment by Delitants** [comment]
> Try removing the .bin file for your CAM from /var/cache/minisatip and try again

No changes:

[25/06 10:52:53.261 AD2]: RECV ciplus cc msg CAM2, session_num 6, tag 9f9007 len 40 dt_id 0
[25/06 10:52:53.261 AD2]: auth ok!
[25/06 10:52:53.261 AD2]: serial sac data req: 4
[25/06 10:52:53.261 AD2]: req element 49
[25/06 10:52:53.261 AD2]: element_get_buf: datatype 49 not valid
[25/06 10:52:53.261 AD2]: can not get element 49
[25/06 10:52:53.261 AD2]: cannot get element 49
[25/06 10:52:53.261 AD2]: cannot req data
[25/06 10:52:54.301 AD2]: READ TPDU: :
  0000  00 01 80 02 01 80

**Comment by Jalle19** [comment]
@Delitants I pushed another commit, can you apply it and try again?

**Comment by Jalle19** [comment]
No, those have been printed all this time. Can you post a complete log?

**Comment by Jalle19** [comment]
Added improved support for operator profiles, hoping that it will shed some light on what needs to be done to make this CAM work. @Delitants please try this branch again at some point. Make sure you actually apply all the changes, I force pushed to the branch so you'll need to remove it and clone again.

**Comment by Jalle19** [comment]
I'm cautiously optimistic that the problem here is that we fail to send element 49 when the CAM requests it, after which it gives up and never sends any further elements. This means we don't get the odd register key later on when needed.

**Comment by Delitants** [comment]
> No, those have been printed all this time. Can you post a complete log?

Please see the log with these changes. It did not fail in first 15 minutes yet.
[minisatip2.log](https://github.com/user-attachments/files/15993823/minisatip2.log)

**Comment by Jalle19** [comment]
Element is correctly send to the CAM now:
```
$ cat minisatip2\(7\).log | grep 'stored 49\|element 49'
[26/06 21:16:24.634 AD2]: _element_set_ stored 49 with len 1
[26/06 21:16:32.829 AD2]: req element 49
```

and as if by magic, the CAM now sends the key for the other register roughly 10 seconds before a parity change:
```
$ cat minisatip2\(7\).log | grep descrambler_set_key
[26/06 21:16:30.485 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 0
[26/06 21:26:22.236 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 1
```

Fuck me, I think it works now :pray:

**Comment by Delitants** [comment]
> Element is correctly sent to the CAM now:
> 
> ```
> $ cat minisatip2\(7\).log | grep 'stored 49\|element 49'
> [26/06 21:16:24.634 AD2]: _element_set_ stored 49 with len 1
> [26/06 21:16:32.829 AD2]: req element 49
> ```
> 
> and as if by magic, the CAM now sends the key for the other register roughly 10 seconds before a parity change:
> 
> ```
> $ cat minisatip2\(7\).log | grep descrambler_set_key
> [26/06 21:16:30.485 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 0
> [26/06 21:26:22.236 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 1
> ```
> 
> Fuck me, I think it works now 🙏

Awesome. Does that mean it will also resolve an issue that I needed to tune to a different channel after one month to re-activate the cam?

**Comment by Jalle19** [comment]
Probably not

**Comment by Delitants** [comment]
> Element is correctly sent to the CAM now:
> 
> ```
> $ cat minisatip2\(7\).log | grep 'stored 49\|element 49'
> [26/06 21:16:24.634 AD2]: _element_set_ stored 49 with len 1
> [26/06 21:16:32.829 AD2]: req element 49
> ```
> 
> and as if by magic, the CAM now sends the key for the other register roughly 10 seconds before a parity change:
> 
> ```
> $ cat minisatip2\(7\).log | grep descrambler_set_key
> [26/06 21:16:30.485 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 0
> [26/06 21:26:22.236 AD2]: === descrambler_set_key === adapter = CA2 key regiser (0-even, 1-odd) = 1
> ```
> 
> Fuck me, I think it works now 🙏

**Not** fixed. Fails during decoding, just with longer intervals now (hours instead of 5-10 minutes).
[minisatip2.log.zip](https://github.com/user-attachments/files/16026209/minisatip2.log.zip)

**Comment by Jalle19** [comment]
Please use a version of minisatip that actually contains this fix
image
```
[27/06 21:53:03.809 AD2]: req element 49
[27/06 21:53:03.809 AD2]: element_get: invalid id
[27/06 21:53:03.809 AD2]: can not get element 49
[27/06 21:53:03.809 AD2]: cannot get element 49
[27/06 21:53:03.809 AD2]: cannot req data
```

**Pull request merged**
