### PR TITLE
Various CI resource tweaks

### PR DESCRIPTION
**Pull request by Jalle19**
~Makes the Kabelio CAM in https://github.com/catalinii/minisatip/issues/910 initialize, although some issues still seem to remain.~

@Yuri666 what do you think?

### CODE REVIEW

**Comment by Yuri666** [comment]
SAS support not unfinished. It sends fake host_id to CAM and end session. Without SAS support some CAMs don't work. I have such CAMs.

**Comment by Yuri666** [comment]
btw, Kabelio CAM still not initialized properly with this changes

**Comment by Yuri666** [comment]
hmm, really. sorry forgot to delete the comment

**Comment by Jalle19** [comment]
Dropped the SAS commit, reworked the resource announcement to not include version 5 of Application Information.

**Comment by Jalle19** [comment]
@Yuri666 what do you think about the remaining changeset? Works for me at least with a 1.4 CAM.

**Comment by Yuri666** [comment]
You remove AI resource announcement, but also remove callback processing this resource. Maybe shall leave callback in code if in futures we'll needs to enable AI v.5, we can only add it at one line.

**Comment by catalinii** [comment]
Do you think this would work faster with remote access?

**Comment by Jalle19** [comment]
@Yuri666 sure, I can leave the callback case values in place.

**Comment by Jalle19** [comment]
@catalinii for https://github.com/catalinii/minisatip/issues/910, yes, probably

**Comment by Yuri666** [comment]
Nice. I suggest also to remove this code, because it wrong:
https://github.com/catalinii/minisatip/blob/master/src/ca.c#L75
https://github.com/catalinii/minisatip/blob/master/src/ca.c#L2849

**Comment by Jalle19** [comment]
@Yuri666 done, good catch!

**Comment by Yuri666** [comment]
> @Yuri666 I had to re-add older host control and content control resources for my other CAM to initialize. Not sure what the best approach here is - clearly it's not possible to go by the recommendation in the spec.

You sure what your CAM needs two versions both resources? Can you make log CAM initialization with -l ca option?

**Comment by Yuri666** [comment]
> @Yuri666 FWIW I implemented the date time resource properly here: https://github.com/catalinii/minisatip/compare/master...Jalle19:datetime-test?expand=1
> 
> Can't say whether it makes any difference, but at least now the date is being sent to the CAM as often as the CAM wants 🤷 Will PR once we can sort out this resource mess.

I made same alredy in test branch in my repository. No filling any difference with my CAMs. It doesn't really matter because CAM takes time from the stream

**Comment by Yuri666** [comment]
> Yeah, if I comment out the older host control and/or content control versions it gets stuck when the CAM is supposed to start the content control stuff.
please try to leave only CIPLUS_APP_DVB_RESOURCEID of dvb control and all as is of content control - is it will work?

**Comment by Jalle19** [comment]
We should try https://github.com/OpenViX/enigma2/blob/58c05ef12d11a98a698c368ae2bde4664b550b8b/lib/dvb_ci/dvbci_resmgr.cpp#L82 since everyone seems to say their stuff works on Enigma 🤷

**Comment by Jalle19** [comment]
> We should try https://github.com/OpenViX/enigma2/blob/58c05ef12d11a98a698c368ae2bde4664b550b8b/lib/dvb_ci/dvbci_resmgr.cpp#L82 since everyone seems to say their stuff works on Enigma shrug

Tried it, got "Your host is not fully CI plus compliant" from the CAM :shrug:

**Comment by Jalle19** [comment]
I dropped the "use the highest version of each resource only" commit since it didn't seem to actually work. Also re-added the handling of AI resource version 5 so it's only a matter of announcing it if we want to try to support it.

**Comment by Jalle19** [comment]
Been using this for a long time locally with my two CAMs, everything seems to work smoothly. I've got other fixes lined up that are based on this branch so I will go ahead and merge this and PR the next batch.

If there are any issues with these please let me know so we can keep master working for everyone!

**Pull request merged**
