### PR TITLE
wrong do_play

### PR DESCRIPTION
**Pull request by 9000h**
use the do_play from the stream

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @9000h ,

You noticed that?
https://github.com/catalinii/minisatip/pull/670/files#diff-b4c34cf7e2b840ebe24729f28a8c5f27L85-L86

Please @catalinii , comment it.

**Comment by 9000h** [comment]
I'm unsure which clients do really rely on that describe info especially outside session, but I think it needs a rewrite to cover both situations.

**Comment by catalinii** [comment]
I am not sure is safe to use sid->do_play as sid can get to be NULL, which will crash the app ?

maybe is better to set do_play just before that ?

**Comment by 9000h** [comment]
is sid2 not already valid inside the if(sid2

**Pull request merged**
