### PR TITLE
please refresh vuplus binaries

### PR DESCRIPTION
**Pull request by cvbasta**

### CODE REVIEW

**Comment by catalinii** [comment]
Hi,

the commits exists already in 0.4.... is this pull request by mistake ?

Thanks

**Comment by cvbasta** [comment]
oh, sorry, i would like to have the newest one 0.5 please.

**Comment by catalinii** [comment]
If you point me to the compiler I can do it by myself...

**Comment by cvbasta** [comment]
I only have this how-to http://blog.videgro.net/2013/05/how-to-compile-software-for-vu-plus/

**Comment by catalinii** [comment]
Try gigablue binary from https://minisatip.org/forum/viewtopic.php?f=5&t=371 and let me know if it works

**Pull request closed without merging**
