### PR TITLE
Define character encoding when serving state.json

### LINKED ISSUE #398: Web-GUI: german umlauts not working in channel names
German umlauts like ü and ö are shown as question mark in column of the stream.
Tested with Google Chrome and Mozilla Firefox.

umlauts

Looks like this names are written with JavaScript, I am not sure if utf8 is possible...

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #398

Before:
Screenshot-20221011145440-1245x388

After:
Screenshot-20221011145139-1243x348

### CODE REVIEW

**Comment by Jalle19** [comment]
@lars18th @Yuri666 care to test this? I have _very few_ service names with "special characters" in them so it's hard to tell if this is a definite fix or not.

**Review by catalinii — APPROVED** [review]

**Comment by Yuri666** [comment]
Not work for my provider:
image
To my provider needs charset=ISO-8859-5:
image

**Comment by Jalle19** [comment]
I think this needs a more complex fix then. The service name needs to be converted to Unicode from the character set indicates in the service information. I'll see if the logic can be easily copied from e.g. tvheadend's implementation.

**Comment by Jalle19** [comment]
This is more than I bargained for so I'll close this for now

**Comment by catalinii** [comment]
Most of tvh implementation seems to be here.
I think the charset is specified as part of the string. Before we bring something complete maybe we can use the encoding that is defined in the SDT. At least for the ppl watching channels from one country it will work.

**Comment by catalinii** [comment]
https://github.com/tvheadend/tvheadend/blob/5f9404117f59ad1f5aa7ca542ce39d9e064e8209/src/input/mpegts/dvb_support.c#L260

**Pull request closed without merging**
