### PR TITLE
Improve RTSP return code parsing

### PR DESCRIPTION
**Pull request by Jalle19**
@retrofan1979 can you try this branch?

### CODE REVIEW

**Comment by retrofan1979** [comment]
Hi, thanks, it looks far better, but still some errors in the logfile?

Channelscan does work now with TransEdit, DVBViewer and Tvheadend. Bravo!

However, I noticed --satip-xml http://192.168.178.1:49000/satipdesc.xml gives 0 devices back instead of 4.
I now manually set the tuners with -s dvbc:192.168.178.1 -s dvbc:192.168.178.1 -s dvbc:192.168.178.1 -s dvbc:192.168.178.1

Also when changing channels in Kodi with TVH client, it looks like the used tuner doesn't respond and after a time-out of 8 seconds, it switches to the next free tuner and then it streams again.

Overal, I'm very happy with this fix, but maybe it needs some more adjustments :-)

I also saw a quirck for Aurora client, but this one is very old and not working anymore and I don't know if it still needs to be in the minisatip source code (missing mtype fix).

[minisatip.zip](https://github.com/user-attachments/files/16581721/minisatip.zip)

**Comment by retrofan1979** [comment]
Hmmm, when streaming a channel after 2-3 minutes the streams stops and then it continues again. See logfile attached.

[minisatip.zip](https://github.com/user-attachments/files/16587906/minisatip.zip)

**Comment by retrofan1979** [comment]
Hmmm, the stream sometimes stops after 1 minute and restarts again when using 4 x -s dvbc:192.168.178.1

**Comment by Jalle19** [comment]
> However, I noticed --satip-xml http://192.168.178.1:49000/satipdesc.xml gives 0 devices back instead of 4. Maybe a bug? I now manually set the tuners with -s dvbc:192.168.178.1 -s dvbc:192.168.178.1 -s dvbc:192.168.178.1 -s dvbc:192.168.178.1
I think this is a known quirk needed for Fritzbox.

The log looks fine to me in general

**Pull request merged**
