### PR TITLE
Revert all recent PMT related changes, restore channel names

### LINKED ISSUE #1000: Channel names missing in web interface
https://github.com/catalinii/minisatip/blob/08c374bab421211df913a061c2fd35e7980eae54/src/pmt.c#L2255
should it be not
strlcatf(dest, max_size, pos, "%s,", pmt->name);
but it shows then all channels on the freq

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #1000

@catalinii maybe we can incorporate some of the changes you've made iteratively so we don't introduce bugs?

### CODE REVIEW

**Comment by Jalle19** [comment]
@9000h does this branch work for you? Are you still seeing channel names?

**Comment by catalinii** [comment]
I would ratger go forward and fix the channel names. I can take a look and see what is missing if you provide a log with -l pmt,tables

**Comment by Jalle19** [comment]
[Uploading minisatip_channel_names.log…]()

@catalinii here you go. Channel name is supposed to be Yle TV1 HD.

**Comment by 9000h** [comment]
I do have channel names with the latest git and also if I do the revert https://patch-diff.githubusercontent.com/raw/catalinii/minisatip/pull/1012.diff

**Comment by 9000h** [comment]
@Jalle19 
[22/10 20:37:32.777 main]: mkdir /var failed
[22/10 20:37:32.777 main]: mkdir /var/cache failed
[22/10 20:37:32.777 main]: mkdir /var/cache/minisatip failed

**Comment by Jalle19** [comment]
@9000h that is unrelated to this issue, it only means `bootid` won't be written

**Comment by 9000h** [comment]
could it be that you have mix of /var/lib/minisatip and /var/cache/minisatip

**Comment by Jalle19** [comment]
FWIW the mkdir error is wrong - in my case it "failed" because the directory already existed

**Comment by Jalle19** [comment]
Incidentally it would be "fixed" with these reverts :D

**Pull request closed without merging**
