### PR TITLE
Omit unsubscribed PIDs from CA PMT

### PR DESCRIPTION
**Pull request by Jalle19**
CAMs generally have an upper limit to have many PIDs can be decrypted. If two services have a very large number of PIDs, the CAM limit may be reached simply by stuffing the PIDs from two PMTs inside a single CA PMT (which happens for the first two channels when the "-c" parameter is used).

Clients can filter out stream PIDs they are not interested in, e.g. with tvheadend using stream filters. However, minisatip does not take into account whether or not a particular PID for a particular service is actually "subscribed to" on the adapter level when creating the CA PMT. This changes that.

Should increase the likelyhood that a CAM can decrypt more than two channels per CA PMT (i.e. using `-c 4:3` instead of `-c 4:2`).

Here's some comparisons with a channel that happens to have a lot of PIDs (six audio tracks, teletext, and three subtitle tracks):

```
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: Dumping pids table for adapter 7, number of unknown pids: 0
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1011, fd 100, packets 178432, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1013, fd 100, packets 10458, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1016, fd 100, packets 6696, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1012, fd 100, packets 5180, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1015, fd 100, packets 2988, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1014, fd 100, packets 3137, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1017, fd 100, packets 2444, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1018, fd 100, packets 1669, d/c errs 0/0, flags 1, pmt 6, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 18, fd 100, packets 1375, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: -1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 0, fd 100, packets 63, d/c errs 0/0, flags 1, pmt -1, filter 2, sock -1, sids: -1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1, fd 100, packets 334, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1271, fd 100, packets 275, d/c errs 0/0, flags 1, pmt -6, filter 15, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 16, fd 100, packets 0, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: -1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 2757, fd 100, packets 333, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1019, fd 100, packets 0, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 48, fd 100, packets 3000, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1272, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 2759, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1021, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1022, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1025, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1023, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1024, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1027, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1028, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:14:13 vladimir minisatip[23853]: [05/12 15:14:13.775 AD1]: pid 1026, fd 0, packets 0, d/c errs 0/0, flags 2, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
```

After:

```
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: Dumping pids table for adapter 1, number of unknown pids: 0
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1011, fd 11, packets 159147, d/c errs 0/0, flags 1, pmt 4, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 18, fd 40, packets 50148, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1013, fd 12, packets 9328, d/c errs 0/0, flags 1, pmt 4, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1016, fd 14, packets 5972, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1014, fd 13, packets 2799, d/c errs 0/0, flags 1, pmt 4, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 48, fd 45, packets 2710, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 16, fd 39, packets 442, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 0, fd 10, packets 298, d/c errs 0/0, flags 1, pmt -1, filter 9, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1271, fd 15, packets 298, d/c errs 0/0, flags 1, pmt -4, filter 12, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1, fd 16, packets 298, d/c errs 0/0, flags 1, pmt -1, filter 14, sock -1, sids: 1 257 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 2757, fd 42, packets 297, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1021, fd 43, packets 3405, d/c errs 2909/0, flags 1, pmt 5, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 17, fd 41, packets 59, d/c errs 0/0, flags 1, pmt -1, filter 10, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1023, fd 44, packets 200, d/c errs 171/0, flags 1, pmt 5, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1024, fd 46, packets 60, d/c errs 51/0, flags 1, pmt 5, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1026, fd 47, packets 128, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 1272, fd 48, packets 6, d/c errs 0/0, flags 1, pmt -5, filter 13, sock -1, sids: 1 -1 -1 -1 -1 -1 -1 -1
Dec 05 15:23:23 vladimir minisatip[24156]: [05/12 15:23:23.096 main]: pid 2759, fd 49, packets 6, d/c errs 0/0, flags 1, pmt -1, filter -1, sock -1, sids: 257 -1 -1 -1 -1 -1 -1 -1
```

@Yuri666 supplied the initial patch, thanks!

### CODE REVIEW

**Comment by Jalle19** [comment]
Forgot to say that I've been running this for months without issues

**Comment by Jalle19** [comment]
Any takers?

**Comment by catalinii** [comment]
I think the in patch is wrong but I understand that it may work sometimes.

The reason this could not work sometimes is that the ddci.c can map the same pid from different adapters to the different pids inside of the generated pmt.

Will try to rework the patch

**Comment by Jalle19** [comment]
Good point, that may indeed cause some issues. Preferable then the PIDs in question should never be mapped to the DDCI virtual PMT in the first place, then this filtering would not have to be done here (which I agree is not where it belongs).

**Comment by catalinii** [comment]
@Jalle19 @Yuri666 can you check if this PR works ?

**Comment by Yuri666** [comment]
Only for DDCI? Not for embedded CI?

**Comment by Jalle19** [comment]
make test is failing

**Comment by catalinii** [comment]
I saw the test are failing,
 just trying to take it step by step and see if there are any side effects

**Comment by Jalle19** [comment]
Might take a few days before I have time to test

**Comment by catalinii** [comment]
Basically I am interested to see if switching between audio tracks works...
@Yuri666 can you test?

**Comment by Yuri666** [comment]
My TBSCI is die

**Comment by Jalle19** [comment]
> Basically I am interested to see if switching between audio tracks works...

In my setup (tvheadend), all the audio PIDs are subscribed to regardless of which audio track is chosen by the downstream client (Kodi), so I don't think I can easily test the new PMT CRC logic you added.

**Comment by Yuri666** [comment]
Partially repaired my tbsci. Made some test with vlc and channel with 2 audio pids. Works bad. Stream with only second apid works only first time start. If before or after is start starts stream with first apid, second apid no decoded with no CW found in log.
Can anybody explain me in which case the root patch works wrong?

**Comment by catalinii** [comment]
There are 2 main issues with the inital patch submitted here:
1) It searches for stream_pids from the PMT in all adapters. In case you are using multiple channels (with dd and without), pids that are not explicitly added by the client using dd can be marked as added making the patch not work.
2) In case of pids conflict (for example u want to decrypt 2 channels from 2 different transponders using the same vpid and apid) ddci.c will map second channel vpid and apid to a new vpid and apid (vpid+1 and apid+1)
In that case if you search for the mapped vpids (apid+1, vpid+1) you will not find them in the original adapters potentially sending an empty PMT to the CAM.

If you watch max 2 channels at the same time is possible you do not see this issue, but changing audio tracks can still be broken using the original patch.

Can you test this scenario (changing audio tracks) with your patch and let me know it it works?

**Comment by Yuri666** [comment]
Initially was mind to reduce numbers pids in CAPMT. Before its mapped to ddci. So mentioned issues should not to be arrived - pids from stream not changed, just number reduced. Maybe I use wrong point to implement.
I will make tests with this patch tomorrow

```
diff --git a/src/pmt.c b/src/pmt.c
index f319040..bc031b6 100644
--- a/src/pmt.c
+++ b/src/pmt.c
@@ -2137,7 +2140,21 @@ int pmt_add_ca_descriptor(SPMT *pmt, uint8_t *buf) {

 int CAPMT_add_PMT(uint8_t *capmt, int len, SPMT *pmt, int cmd_id) {
     int i = 0, pos = 0;
+    int j = 0;
+    SPid *p;
     for (i = 0; i < pmt->stream_pids; i++) {
+p=NULL;
+for (j = 0; j < MAX_ADAPTERS; j++) {
+if(is_adapter_disabled(j))
+continue;
+adapter *ad = get_adapter(j);
+if(ad && ad->tp.freq > 0) //skip ddci device
+p=find_pid(j, pmt->stream_pid[i].pid);
+if(p) //found pid, stop searching
+break;
+}
+if(!p) //pid not found, don't add to capmt
+continue;
         capmt[pos++] = pmt->stream_pid[i].type;
         copy16(capmt, pos, pmt->stream_pid[i].pid);
         pos += 2;
```

**Comment by Yuri666** [comment]
Ok, i made tests. You absolutely right. If I stream same channels with different audio pids I have same issues as I seen with your patch

**Comment by catalinii** [comment]
@Yuri666 can you test now ?

**Comment by Yuri666** [comment]
Works fine at any combinations. Tested only with ddci device.

**Comment by Yuri666** [comment]
Tested. Works without any issues. Fine!

**Pull request merged**
