### PR TITLE
fix dvbapi issue

### PR DESCRIPTION
**Pull request by 9000h**
the last updates here did break  dvbapi

### CODE REVIEW

**Comment by catalinii** [comment]
This changes from the diff are final?

**Comment by 9000h** [comment]
if there is anything else then I do not see it

**Comment by catalinii** [comment]
pmt->stream_pid[pmt->stream_pids++].type = stype;

This will increment stream_pids so the stype and spid will not use the same stream_pids index.

**Comment by 9000h** [comment]
ok then I do not know how to fix it right, do you have proper fix?

**Comment by catalinii** [comment]
The previous code was fine. What issue did you see that you wanted to fix?

**Comment by 9000h** [comment]
I need to do more investigation, the issue was with vdr + satip plugin where encrypted channels did not work as before the last changes.

**Comment by 9000h** [comment]
the issue did happen with server Ubuntu 18.04 minisatip and oscam, client Ubuntu 18.04 kernel 5.02 firefox with 2 open tabs (oscam log, minisatip status) vdr 2.4.0 + satip plugin. 
I do not have detailed logs but I believe it has something to do with firefox as under the same conditions with chromium there is no issue.

**Pull request closed without merging**
