### PR TITLE
Send diseqc command with 18V

### PR DESCRIPTION
**Pull request by lars18th**
When multiple tuners share the same wire in a master-slave configuration, it's preferable to send all diseqc commands using the 18V voltage. Then commands are more easy to read from devices when tuners inject incorrect power or slave tuners are miss configured. This behaviour increase the robustness of the diseqc commands.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @catalinii and @perexg ,

Please check it. This improves the switching in my house using multiple tuners connected to the same wire.

Regards.

**Comment by lars18th** [comment]
Hi,

No comments? Take note that the CI error it's caused by an internal error of the service. The code is clean. In my environment this change has reduced the tunning errors caused by switches to near zero. And the original idea is not mine.

Regards.

**Comment by lars18th** [comment]
Hi,

No one tested this patch ❓ 😮

**Review by Jalle19 — APPROVED** [review]

**Comment by Jalle19** [comment]
Let's close these old pull requests, they can be re-opened if necessary.

**Pull request closed without merging**
