### PR TITLE
Add syslog support, fix unaligned access

### PR DESCRIPTION
**Pull request by perexg**

### CODE REVIEW

**Comment by catalinii** [comment]
Hi,

I will add this .... Thanks for the patch.

**Comment by perexg** [comment]
Thanks. BTW: The HTTP mpegts stream contains extra 0x0d 0x0a bytes before TS data (before first 0x47 sync)..

**Comment by catalinii** [comment]
so you mean there are actually 0d 0a 0d 0a between the last char and the 0x47 ?

Btw, I have merged the pull request in the new commit, but will reject it from here (my version needed some changes to be able to apply this as it is...

**Comment by perexg** [comment]
I see that my code is in commit 1557fb01cef8954406ebaad4f6eb653974826010. It's good habit to keep credits to authors in the open source.

**Comment by catalinii** [comment]
I appologize for that, my intention was not take the credits for your effort, believe me I appreciate it.
I did it because I was too far ahead with the changes for the new commit.

**Comment by perexg** [comment]
Merged to the master, closing.

**Pull request closed without merging**
