### PR TITLE
Adapter allocation / Diseqc changes

### PR DESCRIPTION
**Pull request by perexg**
These three commits are trying to resolve the adapter allocation and enhance the diseqc control.

### CODE REVIEW

**Comment by catalinii** [comment]
Hi perexg,

can you confirm that you tested the changes ?

Thanks

**Comment by perexg** [comment]
Added two more commits - one fix and the first adds handling of * as all adapters (default settings) for the diseqc options.

I tested my changes here.

**Comment by catalinii** [comment]
Thank you ...appreciate it.

**Comment by 9000h** [comment]
a warning shows up here on compile
```
make clean; make DVBCA=yes
rm *.o minisatip >> /dev/null
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o minisatip.o minisatip.c
minisatip.c: In function ‘set_options’:
minisatip.c:454:4: warning: implicit declaration of function ‘set_diseqc_timing’ [-Wimplicit-function-declaration]
    set_diseqc_timing(optarg);
    ^
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o socketworks.o socketworks.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o stream.o stream.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o adapter.o adapter.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o utils.o utils.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o dvbapi.o dvbapi.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o ca.o ca.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o tables.o tables.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o satipc.o satipc.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -c -o dvb.o dvb.c
cc -ggdb -fPIC  -DDISABLE_NETCVCLIENT -o minisatip minisatip.o socketworks.o stream.o adapter.o utils.o dvbapi.o ca.o tables.o satipc.o dvb.o -lpthread -lrt  -ldvbcsa -ldvben50221 -ldvbapi -lucsi
```

**Comment by perexg** [comment]
Fixed in PR#256 .

**Pull request merged**
