### PR TITLE
UI enhancement: show client protocol

### PR DESCRIPTION
**Pull request by lars18th**
Adds support for displaying the protocol used by each client to connect.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi,

This PR implements the pending enhancement described in #940.

**Comment by lars18th** [comment]
And as a bonus it shows the PMT list of channels too.

**Comment by Jalle19** [comment]
Looks good, will try this myself before merging

**Comment by lars18th** [comment]
As a second bonus I've added a more compact size of the columns.

**Review by Jalle19 — COMMENTED** [review]
Can you please use CSS classes instead of inline styles?

**Comment by lars18th** [comment]
> Can you please use CSS classes instead of inline styles?

No because I don't know how to do it. If you know it, then please modify it. Sorry.

**Pull request merged**
