### PR TITLE
Improve operator profile support, including properly parsing operator_tune requests

### LINKED ISSUE #1046: operator_tune_status APDU incorrect
CAM does not get automatically renewed when there is time, have to move it to external tuner every 3 months
Also last version of minisatip no longer creates BIN file for the cam. Why? Or path got changed?

[25/01 08:13:26.412 AD2]: CA 2 ======= MMI menu =======
[25/01 08:13:26.412 AD2]: [UI 0] CAM 4K tivusat
[25/01 08:13:26.412 AD2]: [UI 1]
[25/01 08:13:26.412 AD2]: [UI 2]
[25/01 08:13:26.412 AD2]: [UI 3] The tivusat smartcard is not active or
[25/01 08:13:26.412 AD2]: [UI 4] it has to be reactivated.
[25/01 08:13:26.412 AD2]: [UI 5] Please visit the website [www.tivusat.tv](http://www.tivusat.tv/),
[25/01 08:13:26.412 AD2]: [UI 6] contact the callcenter or follow the
[25/01 08:13:26.412 AD2]: [UI 7] procedure described in the instructions.
[25/01 08:13:26.412 AD2]: [UI 8] (20)

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #1046, hopefully

### CODE REVIEW

**Comment by Jalle19** [comment]
@Yuri666 do you have this CAM? It wants to tune to 12226L @ 36E, 12226L @ 56E or 12188L @ 160E

**Comment by Jalle19** [comment]
@Delitants please also try this branch at some point with the NTV CAM or whatever it is

**Review by catalinii — APPROVED** [review]

**Comment by Yuri666** [comment]
> @Yuri666 do you have this CAM? It wants to tune to 12226L @ 36E, 12226L @ 56E or 12188L @ 160E
CAM needs interaction.
[26/06 22:28:48.358 AD4]: CA 4 ======= MMI menu =======
[26/06 22:28:48.358 AD4]: [UI 0] Viaccess Conditional Access
[26/06 22:28:48.358 AD4]: [UI 1] NTV-PLUS Operator Profile (OP)
[26/06 22:28:48.358 AD4]: [UI 2] Press 'OK' to confirm, 'EXIT' to quit
[26/06 22:28:48.358 AD4]: [UI 3] Do you want to activate the NTV-PLUS Operator Profile for satellite signal?
[26/06 22:28:48.358 AD4]: [UI 4] YES
[26/06 22:28:48.358 AD4]: [UI 5] NO

And now 12226L @ 36E disabled.

**Comment by Yuri666** [comment]
I think better way to enable operator profile - put CAM in TV and use cam menu. Different CAMs use different behaviours to interactions during enable operator profile

**Comment by Jalle19** [comment]
Interesting, can you try this branch and post a complete log with -v ca?

**Comment by Yuri666** [comment]
[minisatip.log](https://github.com/user-attachments/files/15995152/minisatip.log)

**Comment by Delitants** [comment]
> Interesting, can you try this branch and post a complete log with -v ca?

I have no longer NTV cam active, stopped paying for it long time ago. The main concern now is tivusat cam.

**Comment by Jalle19** [comment]
@Yuri666 unfortunate that the CAM requires MMI to activate the profile. The specification says that this should be done using the operator profile command set, where the host has an opportunity to say that it is "non-interactive".

**Comment by Jalle19** [comment]
@Yuri666 any chance you could post another log where you have first activated the profile in a TV, then put the CAM back to minisatip?

**Comment by Jalle19** [comment]
I would like to merge this but don't have a CAM that "speaks" operator profile, so I'm a bit reluctant in case there are runtime issues (like crashes). If anyone wants to test this branch out feel free.

**Comment by Yuri666** [comment]
I enabled operator profile in CAM menu at tv, but now have this error and CAM stop initializing
minisatip3.txt](https://github.com/user-attachments/files/16321361/minisatip3.txt)

**Comment by Jalle19** [comment]
@Yuri666 can you please try again with the latest commit? Also please add `-v ca`

**Comment by Yuri666** [comment]
[minisatip.txt](https://github.com/user-attachments/files/16334408/minisatip.txt)

**Comment by Jalle19** [comment]
@Yuri666 does the CAM work? Hard to say what should be done differently than what we do at the moment, there are no errors and no messages from the CAM. We request an "unattended" operator search so maybe this is normal.

**Comment by Yuri666** [comment]
No, CAM does not work. If you look original code, after CIPLUS_TAG_OPERATOR_STATUS needs to send operator_info_req, but in your code sent CIPLUS_TAG_OPERATOR_SEARCH_START - it's wrong.

**Comment by Jalle19** [comment]
I need to check the specs again, I was under the impression that the old code was wrong.

**Comment by Jalle19** [comment]
@Yuri666 can you please try again with the latest commit? Include `-v ca` again so I can get the hexdump of the operator info in order to reliably implement it.

**Comment by Yuri666** [comment]
[minisatip4.txt](https://github.com/user-attachments/files/16354186/minisatip4.txt)
no response to operator_search_start, needs to check syntax

**Comment by Jalle19** [comment]
Thanks, I'll work on decoding the operator info and will double-check the contents of the operator search start payload.

**Comment by Jalle19** [comment]
@Yuri666 I pushed some new changes, can you please test again and make a new log? I reverted the operator search payload to what it was before, let's see if the CAM reacts differently. Operator information is now also logged.

**Comment by Jalle19** [comment]
@Yuri666 ?

**Comment by Yuri666** [comment]
I'll attach the file later - it's too big. I found another CAM and received a request to configure the transponder. That's all. As far as I remember, this didn't work initially with DDCI. Right now I don't have a card connected with a built-in CI slot. I'll try to connect and test it soon.

**Comment by Jalle19** [comment]
Perhaps you could upload it to the forum if it's too big for GitHub.

Would be great to see if the request to tune is parsed correctly.

**Comment by Yuri666** [comment]
[Uploading 1.log.zip…]()

**Comment by Yuri666** [comment]
[Uploading 1.log.zip…]()

**Comment by Jalle19** [comment]
@Yuri666 your log link doesn't work :/

**Comment by Yuri666** [comment]
[log.zip](https://github.com/user-attachments/files/16468642/log.zip)

**Comment by Jalle19** [comment]
Parsing `operator_info` works fine now:

```
[30/07 00:04:31.726 AD5]: Received operator_info APDU: 
  info valid:                  1
  info version:                0
  cicam original network id:   78
  language code:               RUS
  profile_name:                Tricolor TV
```

And apparently with this code, the operator_search_start is doing something at least, since we're receiving operator_tune:

```
[30/07 00:04:32.999 AD5]: Received operator_tune APDU with 39 descriptor bytes
[30/07 00:04:32.999 AD5]: CAM wants to tune to the following transponder: 12226.00 @ 36.0E, DVB-S QPSK, SR 27500.00, FEC 3/4
[30/07 00:04:32.999 AD5]: CAM wants to tune to the following transponder: 12226.00 @ 56.0E, DVB-S QPSK, SR 27500.00, FEC 3/4
[30/07 00:04:32.999 AD5]: CAM wants to tune to the following transponder: 12188.00 @ 140.0E, DVB-S 8PSK, SR 30000.00, FEC 5/6
```

I pushed a commit to fix the parsing of the polarization value, should work now.

@Yuri666 do you have signal from any of those satellites (36E, 56E, 140E)? I would like to see what happens if we tell the CAM that we tuned successfully and then start a service from one of those transponders (meaning data will start being passed through the CAM). The CAM should send an `operator_search_status` when it's "happy" with the tuning, but it doesn't do it at the moment (probably because we tell it we failed to tune).

**Comment by Yuri666** [comment]
[minisatip5.txt](https://github.com/user-attachments/files/16482345/minisatip5.txt)
[minisatip6.txt](https://github.com/user-attachments/files/16482346/minisatip6.txt)
First log after last changes.
Second log after i changed oprf_data tune_status to:
    uint8_t data_oprf_tune_status[] = {
        0x01, // descruptor number
        0x50, // signal strength and quality
        0x50,
        0x00, // status + 4 bit length
        0x0d,        // length (last 8 bits)
    };
But with no luck. In embedded CI should already works. With DDCI i think needs to send to adapter some PID

**Comment by Jalle19** [comment]
In the second log, there's this:

```
[03/08 20:01:53.221 AD5]: CA 5 ======= MMI menu =======
[03/08 20:01:53.221 AD5]: [UI 0] Tricolor TV profile setup
[03/08 20:01:53.221 AD5]: [UI 1]
[03/08 20:01:53.221 AD5]: [UI 2] Press Ok or Exit to quit
[03/08 20:01:53.221 AD5]: [UI 3] Installation in progress.
[03/08 20:01:53.221 AD5]: [UI 4] Please wait..
[03/08 20:01:53.221 AD5]: ======================
```

And finally a second operator_search_status:

```
[03/08 20:02:10.811 AD5]: Received operator_search_status APDU:
  info version:    0
  profile type:    1
  initialized:     1
  refresh request: 2
  error:           1
```

Did you try an encrypted channel from 12226L? Hard to tell from the logs.

> descriptor_number: This 8-bit field identifies the next unprocessed descriptor number in the operator_tune()
APDU which has not been processed by the Host, a value of 0xff indicates that the Host has reached the end of
the table.

@Yuri666 can you try setting descriptor_number to 0xFF? It should be enough to tune one of the three transponders and indicate that we're done. It might be that we need to actually send the descriptor for 12226L in the operator_tune_status for the CAM to "get" that okay the tune is successful. I'll see what I can do next week regarding this. It could be safest/simplest to store and re-use the descriptor from the operator_tune APDU.

**Comment by Jalle19** [comment]
@Yuri666 just to clarify, have you tried this CAM with this branch in an Enigma box? Does it successfully set up the profile there (`error` should be 0 in the operator_status APDU)?

**Comment by Jalle19** [comment]
Rebasing and merging this, we can continue iterating on it later if we want to

**Pull request merged**
