### PR TITLE
Ensure _GNU_SOURCE is always defined

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes https://github.com/catalinii/minisatip/issues/795

### CODE REVIEW

**Comment by Jalle19** [comment]
Actually, this probably won't fix anything, except make it a bit cleaner perhaps. socket.h for satip-axe has this:

```
#ifdef __USE_GNU
/* Send a VLEN messages as described by VMESSAGES to socket FD.
   Returns the number of datagrams successfully written or -1 for errors.

   This function is a cancellation point and therefore not marked with
   __THROW.  */
extern int sendmmsg (int __fd, struct mmsghdr *__vmessages,
                     unsigned int __vlen, int __flags);
#endif
```

So I guess that since it compiles and doesn't crash, it means the implementation is missing from the kernel, hence glibc gives the caller `errno 38`.

**Comment by Jalle19** [comment]
@catalinii do you want to merge this or should I close it? I guess it's a matter of personal preference how these various macros are defined

**Comment by catalinii** [comment]
I prefer keeping it as it is but if you identifoed something missing in the current approach feel free to let ne know

**Comment by Jalle19** [comment]
Nah, not really. I'll close this, maybe if in the future there are more of these it could be worth defining them all in one place.

**Comment by catalinii** [comment]
Thanks

**Pull request closed without merging**
