### PR TITLE
Obey -M when parsing SAT>IP signal strength values too

### LINKED ISSUE #965: Signal strength and SNR values (doesn't take -M parameters)
When using -M parameter, it doesn't do anything with it when I set the STR/SNR values to 0 for all adapters for example (to get 100%) or any other value in the status page of minisatip on port 8080. Is this a bug?

capture str snr

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #965 

Renamed `snr` to `quality` to make it clear where the odd maximum value (15) comes from (the spec).

@retrofan1979 this should really work now, can you test it?

Server:
Screenshot-20220807112504-166x108
Client (using server via `-s`):
Screenshot-20220807112455-177x121

### CODE REVIEW

**Comment by retrofan1979** [comment]
Sorry, not over here. I never see 100%/100%.
[minisatip.log](https://github.com/catalinii/minisatip/files/9276500/minisatip.log)

**Comment by Jalle19** [comment]
> I assume this commit is present when compiling the source again?

You have to compile a version that includes this commit - it's not enough to compile master. To do that you can `git clone https://github.com/Jalle19/minisatip` and then `git checkout satipc-multiplier`, then compile normally.

**Comment by retrofan1979** [comment]
OK, I see. I usually only compile master indeed. ;-)
git checkout satipc-multiplier gives an error:
fatal: not a git repository (or any of the parent directories): .git

Also: This branch is [10 commits behind] catalinii:master.

**Comment by Jalle19** [comment]
You forgot to enter the `minisatip` directory you just cloned

**Comment by retrofan1979** [comment]
O ofcourse, sorry.
Yes, it works now! Finally, thanks!

**Comment by retrofan1979** [comment]
Another question: can you please also let minisatip set qam parameter if it's not specified by client?
Normally it's qam256 at default, but sometimes it's qam64.

**Comment by Jalle19** [comment]
> Another question: can you please also let minisatip set qam parameter if it's not specified by client? Normally it's qam256 at default, but sometimes it's qam64.

Can you open a separate issue for that?

**Comment by retrofan1979** [comment]
just did

**Review by catalinii — APPROVED** [review]

**Pull request merged**
