### PR TITLE
Download the latest Coverity Scan client before performing the scan

### PR DESCRIPTION
**Pull request by Jalle19**
Let's see if this works

### CODE REVIEW

**Comment by Jalle19** [comment]
@catalinii can you double-check that there's a secret named `COVERITY_SCAN_TOKEN`?

**Comment by catalinii** [comment]
Yes COVERITY_SCAN_TOKEN exists

**Comment by Jalle19** [comment]
@catalinii is it the same value as in your minisatip-build-image repository? I can't find a reason why the downloading of the client doesn't work

**Comment by Jalle19** [comment]
@catalinii can you send me the token via e-mail or WhatsApp or soemthing so I can try this locally?

**Comment by Jalle19** [comment]
Okay so the command works fine, but the token is not being read by GitHub for some reason

**Comment by 9000h** [comment]
not sure but could this help
```
curl \
            --form token=$TOKEN \
```

**Comment by Jalle19** [comment]
It simply doesn't work. @catalinii are you really sure the secret is defined in this project?

**Comment by Jalle19** [comment]
It could be that it won't work for pull requests, otherwise anyone could make a PR that logs the token. We should try changing the action to only run against the master branch (makes more sense anyway) and merge this, then deal with the eventual fallout.

**Comment by Jalle19** [comment]
It passed! https://github.com/catalinii/minisatip/actions/runs/10573195509/job/29292218299

**Pull request merged**
