### PR TITLE
NO-PIDS-ALL support

### PR DESCRIPTION
**Pull request by lars18th**
When your SAT>IP doesn't support "pids=all" or you have troubles with it, then you can prepend the character `~` to the command line (like `-s ~dvbt:192.168.1.3:554`) and then when a client requests all pids, then it receives only pids 0-20.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @catalinii ,

This PR is ready to merge it!

**Comment by catalinii** [comment]
Does this patch work on ant device? If yes can you provide a log?

**Comment by lars18th** [comment]
> Does this patch work on ant device?

Sure! It works with _any_ device! You can try it with your current server. Only add "~" at the start.

> If yes can you provide a log?

No. Sorry! However, the patch is quite simple: it only _translates_ all `pids=all` to `pids=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20`.
Nothing more, nothing less.
:wink:

**Comment by lars18th** [comment]
Hi @catalinii ,

Please, re-read https://github.com/catalinii/minisatip/issues/448#issuecomment-403522855

I do the work. So, why not accept this patch?

**Comment by catalinii** [comment]
Hey @lars18th,

Sorry for late reply, but generally I am a bit busy.

Thanks for the patch

**Pull request merged**
