### PR TITLE
Add --cache-dir, use it for bootid, ddci.conf, etc.

### PR DESCRIPTION
**Pull request by Jalle19**
Add `--cache-dir`, defaulting to `/var/cache/minisatip`. Use it to store various files, such as:
    - bootid
    - ddci.conf
    - CI+ files
    
When running as a systemd service, the working directory may not be set. Same thing with `HOME`. This ensures the application always has a dedicated place to write files to. It also prevents your home directory from being spammed with files of unknown origin.

### CODE REVIEW

**Comment by Jalle19** [comment]
Removed some legacy as well

**Comment by lars18th** [comment]
Hi @Jalle19 ,

Great idea! With this we don't need to have multiple bootid files in the E2 and Linux boxes around the filesystem.

Thank you. I hope @catalinii will test and merge soon.
Regards.

**Comment by Jalle19** [comment]
Would probably be safer to use `MAX_PATH` everywhere, let me know if you want me to change this.

**Comment by Jalle19** [comment]
@catalinii I'm not sure why, but now short options don't work for some reason :shrug: 

```
# ./minisatip -f -l general
./minisatip: option '-l' is ambiguous; possibilities: '-lnb' '-log' '-logfile'
[22/01 20:16:09.244 main]: minisatip version 1.1., compiled in Jan 22 2022 19:59:18, with s2api version: 050B
[22/01 20:16:09.915 main]: Initializing with 5 devices
```

This didn't happen when I tested this locally.

**Comment by Jalle19** [comment]
Fix: https://github.com/catalinii/minisatip/pull/923

**Pull request merged**
